[workspace]

[package]
name = "triptych-cpu-core-no-alloc-wasm-probe"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
triptych-cpu-core = { path = "../../../crates/triptych-cpu-core" }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
