/** Guest-visible constants for the ESP32-hosted Z80 SBC v0.1 profile. */

export const ESP32_SBC_BOOT_ROM_BYTES = 0x100;
export const ESP32_SBC_BOOT_ROM_DISABLE_KEY = 0xa5;

export const ESP32_SBC_SERIAL_DATA_PORT = 0x00;
export const ESP32_SBC_SERIAL_STATUS_PORT = 0x01;
export const ESP32_SBC_SERIAL_STATUS_RX_READY = 0x01;
export const ESP32_SBC_SERIAL_STATUS_TX_READY = 0x02;

export const ESP32_SBC_DISK_COMMAND_STATUS_PORT = 0x10;
export const ESP32_SBC_DISK_DRIVE_PORT = 0x11;
export const ESP32_SBC_DISK_RECORD_0_PORT = 0x12;
export const ESP32_SBC_DISK_RECORD_1_PORT = 0x13;
export const ESP32_SBC_DISK_RECORD_2_PORT = 0x14;
export const ESP32_SBC_DISK_RECORD_3_PORT = 0x15;
export const ESP32_SBC_DISK_DATA_PORT = 0x16;
export const ESP32_SBC_DISK_ERROR_PORT = 0x17;

export const ESP32_SBC_DISK_COMMAND_READ_RECORD = 0x01;
export const ESP32_SBC_DISK_COMMAND_WRITE_RECORD = 0x02;
export const ESP32_SBC_DISK_COMMAND_FLUSH = 0x03;
export const ESP32_SBC_DISK_COMMAND_GET_CAPACITY = 0x04;

export const ESP32_SBC_DISK_STATUS_BUSY = 0x01;
export const ESP32_SBC_DISK_STATUS_DATA_REQUEST = 0x02;
export const ESP32_SBC_DISK_STATUS_ERROR = 0x04;
export const ESP32_SBC_DISK_STATUS_WRITE_PROTECTED = 0x08;
export const ESP32_SBC_DISK_STATUS_MEDIA_PRESENT = 0x10;
export const ESP32_SBC_DISK_STATUS_DIRTY = 0x20;
export const ESP32_SBC_DISK_STATUS_READY = 0x40;

export const ESP32_SBC_DISK_ERROR_NONE = 0x00;
export const ESP32_SBC_DISK_ERROR_DRIVE = 0x01;
export const ESP32_SBC_DISK_ERROR_RECORD = 0x02;
export const ESP32_SBC_DISK_ERROR_COMMAND = 0x03;
export const ESP32_SBC_DISK_ERROR_PROTOCOL = 0x04;
export const ESP32_SBC_DISK_ERROR_WRITE_PROTECTED = 0x05;
export const ESP32_SBC_DISK_ERROR_IO = 0x06;

export const ESP32_SBC_SYSTEM_CONTROL_PORT = 0x20;
export const ESP32_SBC_SYSTEM_STATUS_BOOT_ROM_ENABLED = 0x01;

export const ESP32_SBC_VDP_PORT_FIRST = 0x40;
export const ESP32_SBC_VDP_PORT_LAST = 0x4f;
export const ESP32_SBC_SOUND_PORT_FIRST = 0x50;
export const ESP32_SBC_SOUND_PORT_LAST = 0x57;

export const ESP32_SBC_GUEST_RECORD_BYTES = 128;
export const ESP32_SBC_BACKING_SECTOR_BYTES = 512;
export const ESP32_SBC_RECORDS_PER_BACKING_SECTOR =
  ESP32_SBC_BACKING_SECTOR_BYTES / ESP32_SBC_GUEST_RECORD_BYTES;
