// Generated by tools/generate-embedded-cpu-fixtures.mjs.
// Source: test/conformance/fixtures/*.json
// Do not edit by hand.

use super::{
    ByteImage, BytePatch, CpuExpectation, CpuField, CpuPatch, ExpectedResult, Fixture,
    RamExpectation, RamRange, Stop,
};
use triptych_cpu_core::{IoDirection, IoOperation};

pub(crate) static FIXTURES: &[Fixture] = &[
    Fixture {
        id: "boot-overlay-serial",
        source_sha256: [
            0x62, 0x5a, 0x33, 0x6f, 0x9e, 0xde, 0x16, 0x85, 0xea, 0x94, 0x6b, 0xb1, 0xd2, 0xbf,
            0x5e, 0xd5, 0xfb, 0xf6, 0x92, 0x28, 0x34, 0x8d, 0x81, 0x31, 0xe6, 0xe8, 0xf1, 0x0a,
            0x88, 0x27, 0x54, 0xf0,
        ],
        boot_rom: ByteImage {
            size: 256,
            fill: 0,
            patches: &[BytePatch {
                address: 0,
                bytes: &[62, 118, 50, 13, 0, 62, 65, 211, 0, 62, 165, 211, 32],
            }],
        },
        ram: ByteImage {
            size: 65536,
            fill: 0,
            patches: &[],
        },
        drive: None,
        serial_input: &[],
        initial_cpu: &[],
        max_steps: 32,
        max_tstates: 256,
        interrupts_after_step: &[],
        observe_cpu: &[
            CpuField::A,
            CpuField::Halted,
            CpuField::Iff1,
            CpuField::Iff2,
            CpuField::Imode,
            CpuField::Pc,
            CpuField::R,
        ],
        observe_ram: &[RamRange {
            address: 13,
            length: 1,
        }],
        expected: ExpectedResult {
            stop: Stop::Halt,
            steps: 7,
            tstates: 60,
            cpu: &[
                CpuExpectation {
                    field: CpuField::A,
                    value: 165,
                },
                CpuExpectation {
                    field: CpuField::Halted,
                    value: 1,
                },
                CpuExpectation {
                    field: CpuField::Iff1,
                    value: 0,
                },
                CpuExpectation {
                    field: CpuField::Iff2,
                    value: 0,
                },
                CpuExpectation {
                    field: CpuField::Imode,
                    value: 0,
                },
                CpuExpectation {
                    field: CpuField::Pc,
                    value: 14,
                },
                CpuExpectation {
                    field: CpuField::R,
                    value: 7,
                },
            ],
            boot_rom_enabled: false,
            ram_sha256: [
                0x3e, 0xfd, 0xb9, 0x2e, 0xf6, 0x9b, 0xb1, 0x57, 0xf3, 0x72, 0xa3, 0x69, 0x25, 0x35,
                0xec, 0x12, 0xd0, 0x74, 0x28, 0x3a, 0xc0, 0x8a, 0xdc, 0xdf, 0x73, 0xc7, 0xc5, 0x31,
                0x91, 0x66, 0x12, 0x69,
            ],
            ram: &[RamExpectation {
                address: 13,
                bytes: &[118],
            }],
            drive_sha256: &[],
            serial_output: &[65],
            io: &[
                IoOperation {
                    direction: IoDirection::Write,
                    port: 16640,
                    value: 65,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 42272,
                    value: 165,
                },
            ],
            digest: [
                0xfb, 0x5a, 0xa1, 0xeb, 0xd8, 0xf9, 0xd6, 0x6c, 0xc1, 0xfe, 0x2e, 0xbb, 0x27, 0xc6,
                0xd3, 0xa5, 0x99, 0x74, 0x8f, 0x1c, 0x20, 0xa7, 0x70, 0x68, 0xe0, 0x19, 0xd9, 0x83,
                0xde, 0x37, 0x9b, 0x9c,
            ],
        },
    },
    Fixture {
        id: "cold-boot-disk-persistence",
        source_sha256: [
            0x69, 0x51, 0x79, 0x2a, 0xcc, 0xb3, 0xf0, 0x5c, 0x98, 0xdb, 0x16, 0x65, 0xef, 0xbe,
            0x04, 0xac, 0x7d, 0xcf, 0x13, 0xdd, 0x81, 0x88, 0x0d, 0x8c, 0x21, 0x27, 0x15, 0xe7,
            0xe5, 0xb4, 0x18, 0x13,
        ],
        boot_rom: ByteImage {
            size: 256,
            fill: 0,
            patches: &[BytePatch {
                address: 0,
                bytes: &[
                    243, 49, 254, 255, 175, 211, 17, 211, 18, 211, 19, 211, 20, 211, 21, 62, 1,
                    211, 16, 33, 0, 0, 6, 128, 219, 22, 119, 35, 16, 250, 33, 0, 255, 54, 62, 35,
                    54, 165, 35, 54, 211, 35, 54, 32, 35, 54, 195, 35, 54, 0, 35, 54, 0, 195, 0,
                    255,
                ],
            }],
        },
        ram: ByteImage {
            size: 65536,
            fill: 0,
            patches: &[],
        },
        drive: Some(ByteImage {
            size: 512,
            fill: 0,
            patches: &[
                BytePatch {
                    address: 0,
                    bytes: &[
                        62, 66, 211, 0, 175, 211, 17, 62, 1, 211, 18, 175, 211, 19, 211, 20, 211,
                        21, 62, 2, 211, 16, 6, 128, 62, 90, 211, 22, 16, 252, 62, 3, 211, 16, 62,
                        80, 211, 0, 118,
                    ],
                },
                BytePatch {
                    address: 128,
                    bytes: &[
                        17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17,
                    ],
                },
            ],
        }),
        serial_input: &[],
        initial_cpu: &[],
        max_steps: 1000,
        max_tstates: 20000,
        interrupts_after_step: &[],
        observe_cpu: &[CpuField::Halted, CpuField::Pc, CpuField::Sp],
        observe_ram: &[
            RamRange {
                address: 0,
                length: 39,
            },
            RamRange {
                address: 65280,
                length: 7,
            },
        ],
        expected: ExpectedResult {
            stop: Stop::Halt,
            steps: 817,
            tstates: 8220,
            cpu: &[
                CpuExpectation {
                    field: CpuField::Halted,
                    value: 1,
                },
                CpuExpectation {
                    field: CpuField::Pc,
                    value: 39,
                },
                CpuExpectation {
                    field: CpuField::Sp,
                    value: 65534,
                },
            ],
            boot_rom_enabled: false,
            ram_sha256: [
                0xcb, 0x96, 0x21, 0x2d, 0x9e, 0xbe, 0x35, 0x75, 0x4d, 0xc3, 0x4c, 0xfe, 0xa4, 0xe8,
                0x3c, 0x9c, 0x6f, 0xe9, 0x74, 0x7d, 0x29, 0x57, 0xed, 0x05, 0x75, 0x7e, 0xf8, 0xd5,
                0xb4, 0x05, 0xa7, 0x67,
            ],
            ram: &[
                RamExpectation {
                    address: 0,
                    bytes: &[
                        62, 66, 211, 0, 175, 211, 17, 62, 1, 211, 18, 175, 211, 19, 211, 20, 211,
                        21, 62, 2, 211, 16, 6, 128, 62, 90, 211, 22, 16, 252, 62, 3, 211, 16, 62,
                        80, 211, 0, 118,
                    ],
                },
                RamExpectation {
                    address: 65280,
                    bytes: &[62, 165, 211, 32, 195, 0, 0],
                },
            ],
            drive_sha256: &[[
                0x65, 0xf8, 0x4f, 0xff, 0xfa, 0xc7, 0x9d, 0xf8, 0x44, 0xfa, 0x3b, 0xab, 0x55, 0x1f,
                0xbf, 0xfe, 0x07, 0x84, 0x99, 0x3f, 0xad, 0x1a, 0x92, 0x8a, 0xdf, 0x86, 0xcc, 0xb1,
                0xd4, 0xf6, 0x5c, 0xbb,
            ]],
            serial_output: &[66, 80],
            io: &[
                IoOperation {
                    direction: IoDirection::Write,
                    port: 17,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 18,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 19,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 20,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 21,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 272,
                    value: 1,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 278,
                    value: 62,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 15894,
                    value: 66,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 16918,
                    value: 211,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 54038,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 175,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 44822,
                    value: 211,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 54038,
                    value: 17,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 4374,
                    value: 62,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 15894,
                    value: 1,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 278,
                    value: 211,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 54038,
                    value: 18,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 4630,
                    value: 175,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 44822,
                    value: 211,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 54038,
                    value: 19,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 4886,
                    value: 211,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 54038,
                    value: 20,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 5142,
                    value: 211,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 54038,
                    value: 21,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 5398,
                    value: 62,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 15894,
                    value: 2,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 534,
                    value: 211,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 54038,
                    value: 16,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 4118,
                    value: 6,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 1558,
                    value: 128,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 32790,
                    value: 62,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 15894,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 23062,
                    value: 211,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 54038,
                    value: 22,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 5654,
                    value: 16,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 4118,
                    value: 252,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 64534,
                    value: 62,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 15894,
                    value: 3,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 790,
                    value: 211,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 54038,
                    value: 16,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 4118,
                    value: 62,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 15894,
                    value: 80,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 20502,
                    value: 211,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 54038,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 118,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 30230,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 22,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 42272,
                    value: 165,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 16896,
                    value: 66,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 17,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 274,
                    value: 1,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 19,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 20,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 21,
                    value: 0,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 528,
                    value: 2,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 23062,
                    value: 90,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 784,
                    value: 3,
                },
                IoOperation {
                    direction: IoDirection::Write,
                    port: 20480,
                    value: 80,
                },
            ],
            digest: [
                0xbb, 0xb7, 0x6c, 0xa6, 0xdc, 0x63, 0x5b, 0xf7, 0x5f, 0x0c, 0xd4, 0xdd, 0x68, 0x83,
                0x36, 0x22, 0x0f, 0x7b, 0xc1, 0x05, 0x6f, 0xc4, 0x95, 0xa7, 0x9e, 0xc9, 0x6d, 0xfd,
                0x77, 0xa6, 0x60, 0xea,
            ],
        },
    },
    Fixture {
        id: "flags-conditional-timing",
        source_sha256: [
            0x3e, 0x4a, 0x3c, 0x51, 0xd9, 0xc4, 0xbc, 0x0c, 0x5a, 0xc1, 0x2d, 0xc0, 0xea, 0xd7,
            0x04, 0xdc, 0x17, 0x9d, 0xc1, 0x24, 0x8a, 0x43, 0x25, 0x06, 0xe5, 0xb0, 0xd9, 0xb0,
            0x7b, 0x8d, 0x0b, 0xf9,
        ],
        boot_rom: ByteImage {
            size: 256,
            fill: 0,
            patches: &[BytePatch {
                address: 0,
                bytes: &[175, 32, 2, 40, 2, 62, 255, 118],
            }],
        },
        ram: ByteImage {
            size: 65536,
            fill: 0,
            patches: &[],
        },
        drive: None,
        serial_input: &[],
        initial_cpu: &[],
        max_steps: 16,
        max_tstates: 128,
        interrupts_after_step: &[],
        observe_cpu: &[
            CpuField::A,
            CpuField::FC,
            CpuField::FH,
            CpuField::FN,
            CpuField::FP,
            CpuField::FS,
            CpuField::FX,
            CpuField::FY,
            CpuField::FZ,
            CpuField::Halted,
            CpuField::Pc,
        ],
        observe_ram: &[],
        expected: ExpectedResult {
            stop: Stop::Halt,
            steps: 4,
            tstates: 27,
            cpu: &[
                CpuExpectation {
                    field: CpuField::A,
                    value: 0,
                },
                CpuExpectation {
                    field: CpuField::FC,
                    value: 0,
                },
                CpuExpectation {
                    field: CpuField::FH,
                    value: 0,
                },
                CpuExpectation {
                    field: CpuField::FN,
                    value: 0,
                },
                CpuExpectation {
                    field: CpuField::FP,
                    value: 1,
                },
                CpuExpectation {
                    field: CpuField::FS,
                    value: 0,
                },
                CpuExpectation {
                    field: CpuField::FX,
                    value: 0,
                },
                CpuExpectation {
                    field: CpuField::FY,
                    value: 0,
                },
                CpuExpectation {
                    field: CpuField::FZ,
                    value: 1,
                },
                CpuExpectation {
                    field: CpuField::Halted,
                    value: 1,
                },
                CpuExpectation {
                    field: CpuField::Pc,
                    value: 8,
                },
            ],
            boot_rom_enabled: true,
            ram_sha256: [
                0xde, 0x2f, 0x25, 0x60, 0x64, 0xa0, 0xaf, 0x79, 0x77, 0x47, 0xc2, 0xb9, 0x75, 0x05,
                0xdc, 0x0b, 0x9f, 0x3d, 0xf0, 0xde, 0x4f, 0x48, 0x9e, 0xac, 0x73, 0x1c, 0x23, 0xae,
                0x9c, 0xa9, 0xcc, 0x31,
            ],
            ram: &[],
            drive_sha256: &[],
            serial_output: &[],
            io: &[],
            digest: [
                0xa1, 0x91, 0x3f, 0xd2, 0x5c, 0x99, 0x75, 0x69, 0x87, 0x6e, 0xfc, 0x28, 0x9e, 0xe6,
                0xd3, 0xf3, 0x5a, 0x94, 0x99, 0xd4, 0x99, 0x6c, 0xdc, 0x90, 0xba, 0x2b, 0xa4, 0x73,
                0x25, 0x6b, 0x90, 0x1f,
            ],
        },
    },
    Fixture {
        id: "interrupt-im1",
        source_sha256: [
            0x10, 0x52, 0x5a, 0x8f, 0xd5, 0xba, 0x75, 0x46, 0x5e, 0x19, 0x64, 0x68, 0x40, 0x96,
            0x88, 0xbe, 0xe5, 0x7e, 0x0a, 0x68, 0x22, 0x6f, 0x9f, 0x17, 0xdf, 0x05, 0x1e, 0x1d,
            0x20, 0x6b, 0xc8, 0xe4,
        ],
        boot_rom: ByteImage {
            size: 256,
            fill: 0,
            patches: &[
                BytePatch {
                    address: 0,
                    bytes: &[49, 0, 144, 237, 86, 251, 0, 118],
                },
                BytePatch {
                    address: 56,
                    bytes: &[62, 90, 118],
                },
            ],
        },
        ram: ByteImage {
            size: 65536,
            fill: 0,
            patches: &[],
        },
        drive: None,
        serial_input: &[],
        initial_cpu: &[],
        max_steps: 16,
        max_tstates: 128,
        interrupts_after_step: &[4],
        observe_cpu: &[
            CpuField::A,
            CpuField::Halted,
            CpuField::Iff1,
            CpuField::Iff2,
            CpuField::Imode,
            CpuField::Pc,
            CpuField::Sp,
        ],
        observe_ram: &[RamRange {
            address: 36862,
            length: 2,
        }],
        expected: ExpectedResult {
            stop: Stop::Halt,
            steps: 6,
            tstates: 50,
            cpu: &[
                CpuExpectation {
                    field: CpuField::A,
                    value: 90,
                },
                CpuExpectation {
                    field: CpuField::Halted,
                    value: 1,
                },
                CpuExpectation {
                    field: CpuField::Iff1,
                    value: 0,
                },
                CpuExpectation {
                    field: CpuField::Iff2,
                    value: 0,
                },
                CpuExpectation {
                    field: CpuField::Imode,
                    value: 1,
                },
                CpuExpectation {
                    field: CpuField::Pc,
                    value: 59,
                },
                CpuExpectation {
                    field: CpuField::Sp,
                    value: 36862,
                },
            ],
            boot_rom_enabled: true,
            ram_sha256: [
                0x26, 0x3e, 0xe6, 0x37, 0x03, 0x19, 0x76, 0x77, 0xfe, 0xcb, 0xc6, 0x26, 0x4e, 0xdc,
                0xb4, 0xac, 0x13, 0x62, 0x0a, 0xed, 0xb2, 0x87, 0x2f, 0x28, 0x4f, 0x19, 0x29, 0xc1,
                0x9d, 0x96, 0x77, 0x57,
            ],
            ram: &[RamExpectation {
                address: 36862,
                bytes: &[7, 0],
            }],
            drive_sha256: &[],
            serial_output: &[],
            io: &[],
            digest: [
                0x1f, 0xcb, 0x89, 0x5d, 0xb4, 0x42, 0xec, 0xe8, 0x83, 0x63, 0xfb, 0xfb, 0xcb, 0x59,
                0xe9, 0x29, 0x4b, 0x22, 0x96, 0x0c, 0x7b, 0x1e, 0x75, 0x9b, 0xd9, 0xc5, 0xeb, 0xd5,
                0x66, 0x96, 0x68, 0x6b,
            ],
        },
    },
    Fixture {
        id: "reset-defined-state",
        source_sha256: [
            0xd4, 0x35, 0xfa, 0x60, 0xf4, 0x7f, 0xa6, 0x93, 0x42, 0x0c, 0x34, 0x43, 0x30, 0xef,
            0xc1, 0xba, 0xb4, 0x15, 0xe2, 0x47, 0x55, 0xcd, 0x18, 0x41, 0xd2, 0x2b, 0x9b, 0x30,
            0x34, 0x70, 0xca, 0x76,
        ],
        boot_rom: ByteImage {
            size: 256,
            fill: 0,
            patches: &[BytePatch {
                address: 0,
                bytes: &[118],
            }],
        },
        ram: ByteImage {
            size: 65536,
            fill: 0,
            patches: &[],
        },
        drive: None,
        serial_input: &[],
        initial_cpu: &[
            CpuPatch {
                field: CpuField::Pc,
                value: 4660,
            },
            CpuPatch {
                field: CpuField::Imode,
                value: 2,
            },
            CpuPatch {
                field: CpuField::Iff1,
                value: 1,
            },
            CpuPatch {
                field: CpuField::Iff2,
                value: 1,
            },
            CpuPatch {
                field: CpuField::Halted,
                value: 1,
            },
        ],
        max_steps: 8,
        max_tstates: 64,
        interrupts_after_step: &[],
        observe_cpu: &[
            CpuField::Halted,
            CpuField::Iff1,
            CpuField::Iff2,
            CpuField::Imode,
            CpuField::Pc,
        ],
        observe_ram: &[RamRange {
            address: 0,
            length: 1,
        }],
        expected: ExpectedResult {
            stop: Stop::Halt,
            steps: 1,
            tstates: 4,
            cpu: &[
                CpuExpectation {
                    field: CpuField::Halted,
                    value: 1,
                },
                CpuExpectation {
                    field: CpuField::Iff1,
                    value: 0,
                },
                CpuExpectation {
                    field: CpuField::Iff2,
                    value: 0,
                },
                CpuExpectation {
                    field: CpuField::Imode,
                    value: 0,
                },
                CpuExpectation {
                    field: CpuField::Pc,
                    value: 1,
                },
            ],
            boot_rom_enabled: true,
            ram_sha256: [
                0xde, 0x2f, 0x25, 0x60, 0x64, 0xa0, 0xaf, 0x79, 0x77, 0x47, 0xc2, 0xb9, 0x75, 0x05,
                0xdc, 0x0b, 0x9f, 0x3d, 0xf0, 0xde, 0x4f, 0x48, 0x9e, 0xac, 0x73, 0x1c, 0x23, 0xae,
                0x9c, 0xa9, 0xcc, 0x31,
            ],
            ram: &[RamExpectation {
                address: 0,
                bytes: &[0],
            }],
            drive_sha256: &[],
            serial_output: &[],
            io: &[],
            digest: [
                0x08, 0x49, 0x82, 0xb7, 0x3b, 0xdc, 0xef, 0xf9, 0x1d, 0x3c, 0x24, 0xf8, 0x61, 0x29,
                0xba, 0x38, 0xf4, 0x9b, 0xdd, 0xe6, 0x9b, 0x2a, 0xcd, 0x6c, 0x48, 0xcc, 0x97, 0x58,
                0xd7, 0xfe, 0x32, 0xa6,
            ],
        },
    },
    Fixture {
        id: "serial-read-order",
        source_sha256: [
            0xb7, 0xe2, 0xe3, 0x84, 0x4e, 0xff, 0x6e, 0x5f, 0x3b, 0xee, 0xbe, 0x03, 0xb0, 0x60,
            0x64, 0xc6, 0x0b, 0x27, 0x73, 0x87, 0xa3, 0x42, 0x76, 0x4d, 0x1e, 0x58, 0xbc, 0x11,
            0xd6, 0xa5, 0xaa, 0x60,
        ],
        boot_rom: ByteImage {
            size: 256,
            fill: 0,
            patches: &[BytePatch {
                address: 0,
                bytes: &[62, 18, 219, 1, 219, 0, 118],
            }],
        },
        ram: ByteImage {
            size: 65536,
            fill: 0,
            patches: &[],
        },
        drive: None,
        serial_input: &[66],
        initial_cpu: &[],
        max_steps: 16,
        max_tstates: 128,
        interrupts_after_step: &[],
        observe_cpu: &[CpuField::A, CpuField::Halted, CpuField::Pc],
        observe_ram: &[],
        expected: ExpectedResult {
            stop: Stop::Halt,
            steps: 4,
            tstates: 33,
            cpu: &[
                CpuExpectation {
                    field: CpuField::A,
                    value: 66,
                },
                CpuExpectation {
                    field: CpuField::Halted,
                    value: 1,
                },
                CpuExpectation {
                    field: CpuField::Pc,
                    value: 7,
                },
            ],
            boot_rom_enabled: true,
            ram_sha256: [
                0xde, 0x2f, 0x25, 0x60, 0x64, 0xa0, 0xaf, 0x79, 0x77, 0x47, 0xc2, 0xb9, 0x75, 0x05,
                0xdc, 0x0b, 0x9f, 0x3d, 0xf0, 0xde, 0x4f, 0x48, 0x9e, 0xac, 0x73, 0x1c, 0x23, 0xae,
                0x9c, 0xa9, 0xcc, 0x31,
            ],
            ram: &[],
            drive_sha256: &[],
            serial_output: &[],
            io: &[
                IoOperation {
                    direction: IoDirection::Read,
                    port: 4609,
                    value: 3,
                },
                IoOperation {
                    direction: IoDirection::Read,
                    port: 768,
                    value: 66,
                },
            ],
            digest: [
                0x6c, 0xd3, 0x6c, 0xa1, 0x8d, 0x49, 0xd6, 0xd0, 0x57, 0xfa, 0x61, 0x97, 0xaa, 0x50,
                0x60, 0xfa, 0xeb, 0xa4, 0x9c, 0xb4, 0xc1, 0x6e, 0x79, 0xc0, 0xef, 0xc2, 0xf0, 0x74,
                0xcc, 0xf9, 0x77, 0x21,
            ],
        },
    },
];
